name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      project_key: ${{ vars.PROJECT_KEY }}
      organization_key: ${{ vars.ORGANIZATION_KEY }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    if: github.event_name == 'push'
    needs: build
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: github-action
      image_tag: ${{ github.run_number }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  helm:
    if: github.event_name == 'push'
    needs: docker
    uses: ./.github/workflows/reusable-helm.yml
    with:
      chart_path: github-action
      chart_name: github-action-chart
      image_tag: ${{ github.run_number }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}